# SWAHILI SENTIMENT ANALYZER

# Libraries

In [21]:
import pandas as pd
import re
import nltk
import csv
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\User\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\User\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

True

In [22]:
!pip install nltk
!pip install scikit-learn

Requirement already satisfied: nltk in c:\users\user\anaconda3\new folder\lib\site-packages (3.7)
Requirement already satisfied: joblib in c:\users\user\anaconda3\new folder\lib\site-packages (from nltk) (1.1.0)
Requirement already satisfied: click in c:\users\user\anaconda3\new folder\lib\site-packages (from nltk) (8.0.4)
Requirement already satisfied: regex>=2021.8.3 in c:\users\user\anaconda3\new folder\lib\site-packages (from nltk) (2022.7.9)
Requirement already satisfied: tqdm in c:\users\user\anaconda3\new folder\lib\site-packages (from nltk) (4.64.1)
Requirement already satisfied: colorama in c:\users\user\anaconda3\new folder\lib\site-packages (from click->nltk) (0.4.5)
Requirement already satisfied: scikit-learn in c:\users\user\anaconda3\new folder\lib\site-packages (0.24.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\user\anaconda3\new folder\lib\site-packages (from scikit-learn) (2.2.0)
Requirement already satisfied: joblib>=0.11 in c:\users\user\anaconda3\new folder\lib\site-packages (from scikit-learn) (1.1.0)
Requirement already satisfied: scipy>=0.19.1 in c:\users\user\anaconda3\new folder\lib\site-packages (from scikit-learn) (1.9.1)
Requirement already satisfied: numpy>=1.13.3 in c:\users\user\anaconda3\new folder\lib\site-packages (from scikit-learn) (1.21.5)

In [12]:
import nltk

nltk.download('swahili-sentiment')
nltk.download('vader_lexicon')

[nltk_data] Error loading swahili-sentiment: Package 'swahili-
[nltk_data]     sentiment' not found in index
[nltk_data] Downloading package vader_lexicon to
[nltk_data]     C:\Users\User\AppData\Roaming\nltk_data...

True

In [23]:
df = pd.read_csv("swahili.csv")

# Loaded data with labels

In [24]:
df.head(10)

   Unnamed: 0                                               text    labels
0           0                 team 2019merimera alikuwa takataka  negative
1           1                                     sijafurahishwa  negative
2           2                                      kubuni dosari  negative
3           3                  bila kusema nilipoteza pesa zangu  negative
4           4                       sema kupoteza pesa na wakati  negative
5           5  ubunifu ni isiyo ya kawaida sana kwani kipande...  negative
6           6                                  akili yako imeoza  negative
7           7                            aki si maisha ni magumu  negative
8           8                           enyewe safaricom ni wezi  negative
9           9  mtandao duni hata line yao niliweka nyuma ya s...  negative

# Remove URLS

In [25]:
def remove_urls(text):
    url_pattern = re.compile(r'https?://\S+|www\.\S+')
    return url_pattern.sub('', text)

df['text'] = df['text'].apply(remove_urls)
df.head(10)

   Unnamed: 0                                               text    labels
0           0                 team 2019merimera alikuwa takataka  negative
1           1                                     sijafurahishwa  negative
2           2                                      kubuni dosari  negative
3           3                  bila kusema nilipoteza pesa zangu  negative
4           4                       sema kupoteza pesa na wakati  negative
5           5  ubunifu ni isiyo ya kawaida sana kwani kipande...  negative
6           6                                  akili yako imeoza  negative
7           7                            aki si maisha ni magumu  negative
8           8                           enyewe safaricom ni wezi  negative
9           9  mtandao duni hata line yao niliweka nyuma ya s...  negative

# Remove Special Characters

In [26]:
#Remove special characters
def remove_special_characters(text):
    pattern = r'[^a-zA-Z0-9\s]' # keep only alphanumeric and whitespace characters
    text = re.sub(pattern, '', text)
    return text

df['text'] = df['text'].apply(remove_special_characters)
df.head(10)

   Unnamed: 0                                               text    labels
0           0                 team 2019merimera alikuwa takataka  negative
1           1                                     sijafurahishwa  negative
2           2                                      kubuni dosari  negative
3           3                  bila kusema nilipoteza pesa zangu  negative
4           4                       sema kupoteza pesa na wakati  negative
5           5  ubunifu ni isiyo ya kawaida sana kwani kipande...  negative
6           6                                  akili yako imeoza  negative
7           7                            aki si maisha ni magumu  negative
8           8                           enyewe safaricom ni wezi  negative
9           9  mtandao duni hata line yao niliweka nyuma ya s...  negative

# Convert text to lower case

In [31]:
df['text'] = df['text'].str.lower()
df.head(10)

,Unnamed: 0,text,labels,tokens
0,0,team 2019merimera alikuwa takataka,negative,"[team, 2019merimera, takataka]"
1,1,sijafurahishwa,negative,[sijafurahishwa]
2,2,kubuni dosari,negative,"[kubuni, dosari]"
3,3,bila kusema nilipoteza pesa zangu,negative,"[kusema, nilipoteza, pesa, zangu]"
4,4,sema kupoteza pesa na wakati,negative,"[sema, kupoteza, pesa]"
5,5,ubunifu ni isiyo ya kawaida sana kwani kipande...,negative,"[ubunifu, isiyo, kawaida, kwani, kipande, siki..."
6,6,akili yako imeoza,negative,"[akili, yako, imeoza]"
7,7,aki si maisha ni magumu,negative,"[aki, si, maisha, magumu]"
8,8,enyewe safaricom ni wezi,negative,"[enyewe, safaricom, wezi]"
9,9,mtandao duni hata line yao niliweka nyuma ya s...,negative,"[mtandao, duni, line, niliweka, nyuma, simu, y..."

# Tokenize the data

In [32]:
df['tokens'] = df['text'].apply(nltk.word_tokenize)
df.head()

,Unnamed: 0,text,labels,tokens
0,0,team 2019merimera alikuwa takataka,negative,"[team, 2019merimera, alikuwa, takataka]"
1,1,sijafurahishwa,negative,[sijafurahishwa]
2,2,kubuni dosari,negative,"[kubuni, dosari]"
3,3,bila kusema nilipoteza pesa zangu,negative,"[bila, kusema, nilipoteza, pesa, zangu]"
4,4,sema kupoteza pesa na wakati,negative,"[sema, kupoteza, pesa, na, wakati]"

# Remove stopwords

In [33]:
nltk.download('stopwords')
import nltk
nltk.data.path
from nltk.corpus import stopwords

def remove_stopwords(tokens):
    stopwords_list = stopwords.words('swahili')
    filtered_tokens = [token for token in tokens if token.lower() not in stopwords_list]
    return filtered_tokens

df['tokens'] = df['tokens'].apply(remove_stopwords)

df.head()

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\User\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

,Unnamed: 0,text,labels,tokens
0,0,team 2019merimera alikuwa takataka,negative,"[team, 2019merimera, takataka]"
1,1,sijafurahishwa,negative,[sijafurahishwa]
2,2,kubuni dosari,negative,"[kubuni, dosari]"
3,3,bila kusema nilipoteza pesa zangu,negative,"[kusema, nilipoteza, pesa, zangu]"
4,4,sema kupoteza pesa na wakati,negative,"[sema, kupoteza, pesa]"

# Training the model: Using a machine learning algorithm such as a Naive Bayes or SupportVector Machine (SVM) to train a model to classify the text into one of the three sentimentcategories

In [35]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer
df.head()

,Unnamed: 0,text,labels,tokens
0,0,team 2019merimera alikuwa takataka,negative,"[team, 2019merimera, takataka]"
1,1,sijafurahishwa,negative,[sijafurahishwa]
2,2,kubuni dosari,negative,"[kubuni, dosari]"
3,3,bila kusema nilipoteza pesa zangu,negative,"[kusema, nilipoteza, pesa, zangu]"
4,4,sema kupoteza pesa na wakati,negative,"[sema, kupoteza, pesa]"

# Split the data into training and testing sets

In [37]:
X_train, X_test, y_train, y_test = train_test_split(df['text'], df['labels'], test_size=0.2, random_state=42)
df.head()

,Unnamed: 0,text,labels,tokens
0,0,team 2019merimera alikuwa takataka,negative,"[team, 2019merimera, takataka]"
1,1,sijafurahishwa,negative,[sijafurahishwa]
2,2,kubuni dosari,negative,"[kubuni, dosari]"
3,3,bila kusema nilipoteza pesa zangu,negative,"[kusema, nilipoteza, pesa, zangu]"
4,4,sema kupoteza pesa na wakati,negative,"[sema, kupoteza, pesa]"

# Convert the text data into a numerical format using CountVectorizer

In [38]:
vectorizer = CountVectorizer(stop_words='swahili')
swahili_stop_words = ["kwamba", "ni", "ya", "kwa", "na", ...]  
vectorizer = CountVectorizer(stop_words=swahili_stop_words)
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)
df.head()

,Unnamed: 0,text,labels,tokens
0,0,team 2019merimera alikuwa takataka,negative,"[team, 2019merimera, takataka]"
1,1,sijafurahishwa,negative,[sijafurahishwa]
2,2,kubuni dosari,negative,"[kubuni, dosari]"
3,3,bila kusema nilipoteza pesa zangu,negative,"[kusema, nilipoteza, pesa, zangu]"
4,4,sema kupoteza pesa na wakati,negative,"[sema, kupoteza, pesa]"

# Train a Naive Bayes classifier on the training data

In [39]:
clf = MultinomialNB()
clf.fit(X_train_vec, y_train)
df.head()

,Unnamed: 0,text,labels,tokens
0,0,team 2019merimera alikuwa takataka,negative,"[team, 2019merimera, takataka]"
1,1,sijafurahishwa,negative,[sijafurahishwa]
2,2,kubuni dosari,negative,"[kubuni, dosari]"
3,3,bila kusema nilipoteza pesa zangu,negative,"[kusema, nilipoteza, pesa, zangu]"
4,4,sema kupoteza pesa na wakati,negative,"[sema, kupoteza, pesa]"

# Evaluate the classifier on the testing data

In [40]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# Predict the sentiment labels for the testing data
y_pred = clf.predict(X_test_vec)

# Calculate the accuracy of the classifier
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Calculate the precision of the classifier
precision = precision_score(y_test, y_pred, average='macro')
print("Precision:", precision)

# Calculate the recall of the classifier
recall = recall_score(y_test, y_pred, average='macro')
print("Recall:", recall)

# Calculate the F1-score of the classifier
f1_score = f1_score(y_test, y_pred, average='macro')
print("F1-score:", f1_score)
df.head(10)

Accuracy: 0.7770700636942676
Precision: 0.7769445130110558
Recall: 0.7769085382487042
F1-score: 0.7769252628587666

,Unnamed: 0,text,labels,tokens
0,0,team 2019merimera alikuwa takataka,negative,"[team, 2019merimera, takataka]"
1,1,sijafurahishwa,negative,[sijafurahishwa]
2,2,kubuni dosari,negative,"[kubuni, dosari]"
3,3,bila kusema nilipoteza pesa zangu,negative,"[kusema, nilipoteza, pesa, zangu]"
4,4,sema kupoteza pesa na wakati,negative,"[sema, kupoteza, pesa]"
5,5,ubunifu ni isiyo ya kawaida sana kwani kipande...,negative,"[ubunifu, isiyo, kawaida, kwani, kipande, siki..."
6,6,akili yako imeoza,negative,"[akili, yako, imeoza]"
7,7,aki si maisha ni magumu,negative,"[aki, si, maisha, magumu]"
8,8,enyewe safaricom ni wezi,negative,"[enyewe, safaricom, wezi]"
9,9,mtandao duni hata line yao niliweka nyuma ya s...,negative,"[mtandao, duni, line, niliweka, nyuma, simu, y..."

# Training the Support Vector Machine model with a higher max_iter parameter

In [41]:
from sklearn.svm import SVC

# Create an SVM classifier object with a higher max_iter parameter
svm_clf = SVC(kernel='linear', C=1, max_iter=30000)

# Train the SVM classifier on the training data
svm_clf.fit(X_train_vec, y_train)

# Evaluate the SVM classifier on the testing data
svm_acc = svm_clf.score(X_test_vec, y_test)

print("Accuracy of SVM classifier: {:.2f}%".format(svm_acc * 100))
df.head(10)

Accuracy of SVM classifier: 81.15%

,Unnamed: 0,text,labels,tokens
0,0,team 2019merimera alikuwa takataka,negative,"[team, 2019merimera, takataka]"
1,1,sijafurahishwa,negative,[sijafurahishwa]
2,2,kubuni dosari,negative,"[kubuni, dosari]"
3,3,bila kusema nilipoteza pesa zangu,negative,"[kusema, nilipoteza, pesa, zangu]"
4,4,sema kupoteza pesa na wakati,negative,"[sema, kupoteza, pesa]"
5,5,ubunifu ni isiyo ya kawaida sana kwani kipande...,negative,"[ubunifu, isiyo, kawaida, kwani, kipande, siki..."
6,6,akili yako imeoza,negative,"[akili, yako, imeoza]"
7,7,aki si maisha ni magumu,negative,"[aki, si, maisha, magumu]"
8,8,enyewe safaricom ni wezi,negative,"[enyewe, safaricom, wezi]"
9,9,mtandao duni hata line yao niliweka nyuma ya s...,negative,"[mtandao, duni, line, niliweka, nyuma, simu, y..."

# Evaluate the Support Vector Machine model

In [44]:
# Import necessary libraries
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix

# Load the iris dataset
iris = load_iris()

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.3, random_state=42)

# Create an SVM model and fit it to the training data
svm = SVC(kernel='linear', C=1)
svm.fit(X_train, y_train)

# Make predictions on the testing data
y_pred = svm.predict(X_test)

# Print the confusion matrix and classification report
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))
df.head(10)

Confusion Matrix:
[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

,Unnamed: 0,text,labels,tokens
0,0,team 2019merimera alikuwa takataka,negative,"[team, 2019merimera, takataka]"
1,1,sijafurahishwa,negative,[sijafurahishwa]
2,2,kubuni dosari,negative,"[kubuni, dosari]"
3,3,bila kusema nilipoteza pesa zangu,negative,"[kusema, nilipoteza, pesa, zangu]"
4,4,sema kupoteza pesa na wakati,negative,"[sema, kupoteza, pesa]"
5,5,ubunifu ni isiyo ya kawaida sana kwani kipande...,negative,"[ubunifu, isiyo, kawaida, kwani, kipande, siki..."
6,6,akili yako imeoza,negative,"[akili, yako, imeoza]"
7,7,aki si maisha ni magumu,negative,"[aki, si, maisha, magumu]"
8,8,enyewe safaricom ni wezi,negative,"[enyewe, safaricom, wezi]"
9,9,mtandao duni hata line yao niliweka nyuma ya s...,negative,"[mtandao, duni, line, niliweka, nyuma, simu, y..."

# Loading the trained Support Vector Machine model

In [62]:
# Load the training data from a CSV file
train_data = pd.read_csv("swahili.csv")

# Define the vectorizer
vectorizer = TfidfVectorizer()

# Fit the vectorizer on the training data
vectorizer.fit(train_data['text'])

# Transform the training data
train_vectors = vectorizer.transform(train_data['text'])

# Define the LinearSVC model
svm_model = LinearSVC()

# Train the model on the training data
svm_model.fit(train_vectors, train_data['labels'])

# Process the new tweet
tweet = "Nimefurahi sana na 510 na sijakuwa na malalamiko yoyote Kutoka kwa mtu yeyote kuhusu ubora wa sauti"
new_tweet_vector = vectorizer.transform([tweet])

# Predict the sentiment of the new tweet
new_tweet_sentiment = svm_model.predict(new_tweet_vector)

# Print the sentiment of the new tweet
print("The label of this Swahili text is: " + new_tweet_sentiment[0])

train_data.head(10)

The label of this Swahili text is: positive

   Unnamed: 0                                               text    labels
0           0                 team 2019merimera alikuwa takataka  negative
1           1                                     sijafurahishwa  negative
2           2                                      kubuni dosari  negative
3           3                  bila kusema nilipoteza pesa zangu  negative
4           4                       sema kupoteza pesa na wakati  negative
5           5  ubunifu ni isiyo ya kawaida sana kwani kipande...  negative
6           6                                  akili yako imeoza  negative
7           7                            aki si maisha ni magumu  negative
8           8                           enyewe safaricom ni wezi  negative
9           9  mtandao duni hata line yao niliweka nyuma ya s...  negative

# Deploying

In [5]:
import gradio as gr

def predict_sentiment(tweet):
    # Process the new tweet
    new_tweet_vector = vectorizer.transform([tweet])

    # Predict the sentiment of the new tweet
    new_tweet_sentiment = svm_model.predict(new_tweet_vector)

    return new_tweet_sentiment[0]

tweet_input = gr.inputs.Textbox(lines=3, label="Enter your tweet")
prediction = gr.outputs.Label(label="The Sentiment of this tweet is : ")

gradio_interface = gr.Interface(fn=predict_sentiment, inputs=tweet_input, outputs=prediction, title='Swahili Sentiment Analyzer', 
             description='Enter a swahili text to get its sentiment')
gradio_interface.launch(share=True)

C:\Users\User\anaconda3\New folder\lib\site-packages\gradio\inputs.py:27: UserWarning: Usage of gradio.inputs is deprecated, and will not be supported in the future, please import your component from gradio.components
  warnings.warn(
C:\Users\User\anaconda3\New folder\lib\site-packages\gradio\deprecation.py:40: UserWarning: `optional` parameter is deprecated, and it has no effect
  warnings.warn(value)
C:\Users\User\anaconda3\New folder\lib\site-packages\gradio\deprecation.py:40: UserWarning: `numeric` parameter is deprecated, and it has no effect
  warnings.warn(value)
C:\Users\User\anaconda3\New folder\lib\site-packages\gradio\outputs.py:197: UserWarning: Usage of gradio.outputs is deprecated, and will not be supported in the future, please import your components from gradio.components
  warnings.warn(
C:\Users\User\anaconda3\New folder\lib\site-packages\gradio\deprecation.py:40: UserWarning: The 'type' parameter has been deprecated. Use the Number component instead.
  warnings.warn(value)

Running on local URL:  http://127.0.0.1:7867

Could not create share link. Please check your internet connection or our status page: https://status.gradio.app